server:
  port: 8888
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/isrm?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

